### PR TITLE
:memo: v4 logo on main readme

### PR DESCRIPTION
**Pull request by vikiival**
Screenshot 2023-10-26 at 15 42 39

### CODE REVIEW

**Comment by vikiival** [comment]
also cc @kodadot/design-squad

**Comment by exezbcz** [comment]
yes, let me create a nice banner for you sir

**Comment by exezbcz** [comment]
you have the right to choose @vikiival 
image

Twitter header - 6

**Comment by yangwao** [comment]
- https://github.com/kodadot/.github/commit/d9b8f498bfe47a0ae7cf1bca417759153550c5b8

**Pull request closed without merging**
